#pragma warning disable 0649
//This script is generated by jhg's DataGenerator.

using Newtonsoft.Json;

public class DataTown : IBaseData
{
    [JsonProperty(PropertyName = "id")]
    private readonly int id;
    [JsonProperty(PropertyName = "TownScene")]
    public readonly SceneDefine TownScene;
    [JsonProperty(PropertyName = "BGM")]
    public readonly string BGM;
    [JsonProperty(PropertyName = "PortalDungeon")]
    public readonly DungeonDefine PortalDungeon;
	
	public int Id => id;
    public bool IsEmpty => id == 0;
}
