#pragma warning disable 0649
//This script is generated by jhg's DataGenerator.

using Newtonsoft.Json;

public class DataBattleCard : IBaseData
{
    [JsonProperty(PropertyName = "id")]
    private readonly int id;
    [JsonProperty(PropertyName = "CardType")]
    public readonly BattleCardType CardType;
    [JsonProperty(PropertyName = "Tier")]
    public readonly BattleCardTier Tier;
    [JsonProperty(PropertyName = "Ability")]
    public readonly AbilityDefine Ability;
    [JsonProperty(PropertyName = "IconPath")]
    public readonly string IconPath;
    [JsonProperty(PropertyName = "Name")]
    public readonly LocalizationDefine Name;
    [JsonProperty(PropertyName = "Desc")]
    public readonly LocalizationDefine Desc;
	
	public int Id => id;
    public bool IsNull => id == 0;
}
