#pragma warning disable 0649
//This script is generated by jhg's DataGenerator.

using Newtonsoft.Json;

public class DataEquipment : IBaseData
{
    [JsonProperty(PropertyName = "id")]
    private readonly int id;
    [JsonProperty(PropertyName = "EquipmentType")]
    public readonly EquipmentType EquipmentType;
    [JsonProperty(PropertyName = "Name")]
    public readonly LocalizationDefine Name;
    [JsonProperty(PropertyName = "PartsData")]
    public readonly CharacterPartsDefine PartsData;
    [JsonProperty(PropertyName = "Ability")]
    public readonly AbilityDefine Ability;
    [JsonProperty(PropertyName = "AttackAnimState")]
    public readonly CharacterAnimState AttackAnimState;
	
	public int Id => id;
    public bool IsEmpty => id == 0;
}
