#pragma warning disable 0649
//This script is generated by jhg's DataGenerator.

using Newtonsoft.Json;

public class DataDungeon : IBaseData
{
    [JsonProperty(PropertyName = "id")]
    private readonly int id;
    [JsonProperty(PropertyName = "EnemyGroup")]
    public readonly EnemyGroupDefine EnemyGroup;
	
	public int Id => id;
    public bool IsNull => id == 0;
}
