#pragma warning disable 0649
//This script is generated by jhg's DataGenerator.

using Newtonsoft.Json;

public class DataAbility : IBaseData
{
    [JsonProperty(PropertyName = "id")]
    private readonly int id;
    [JsonProperty(PropertyName = "SlotType")]
    public readonly AbilitySlotType SlotType;
    [JsonProperty(PropertyName = "CastingType")]
    public readonly CastingType CastingType;
    [JsonProperty(PropertyName = "BattleEvents")]
    public readonly BattleEventDefine[] BattleEvents;
    [JsonProperty(PropertyName = "TriggerType")]
    public readonly BattleEventTriggerType TriggerType;
    [JsonProperty(PropertyName = "TargetType")]
    public readonly BattleEventTargetType TargetType;
    [JsonProperty(PropertyName = "CastEffectPath")]
    public readonly string CastEffectPath;
    [JsonProperty(PropertyName = "TriggerUnitPath")]
    public readonly string TriggerUnitPath;
    [JsonProperty(PropertyName = "IconPath")]
    public readonly string IconPath;
    [JsonProperty(PropertyName = "HitEffectPrefabName")]
    public readonly string HitEffectPrefabName;
	
	public int Id => id;
    public bool IsEmpty => id == 0;
}
