#pragma warning disable 0649
//This script is generated by jhg's DataGenerator.

using Newtonsoft.Json;

public class DataLocalization : IBaseData
{
    [JsonProperty(PropertyName = "id")]
    private readonly int id;
    [JsonProperty(PropertyName = "Korean")]
    public readonly string Korean;
    [JsonProperty(PropertyName = "English")]
    public readonly string English;
    [JsonProperty(PropertyName = "SimplifiedChinese")]
    public readonly string SimplifiedChinese;
	
	public int Id => id;
    public bool IsNull => id == 0;
}
