#pragma warning disable 0649
//This script is generated by jhg's DataGenerator.

using Newtonsoft.Json;

public struct DataBattleEvent : IBaseData
{
    [JsonProperty(PropertyName = "id")]
    private readonly int id;
    [JsonProperty(PropertyName = "nameId")]
    private readonly string nameId;
    [JsonProperty(PropertyName = "Type")]
    public readonly BattleEventType Type;
    [JsonProperty(PropertyName = "TriggerType")]
    public readonly BattleEventTriggerType TriggerType;
    [JsonProperty(PropertyName = "TargetType")]
    public readonly BattleEventTargetType TargetType;
    [JsonProperty(PropertyName = "PrefabName")]
    public readonly string PrefabName;
    [JsonProperty(PropertyName = "HitEffectPrefabName")]
    public readonly string HitEffectPrefabName;
	
	public int Id => id;
    public string NameId => nameId;
    public bool IsNull => id == 0 || string.IsNullOrEmpty(nameId);
}
