#pragma warning disable 0649
//This script is generated by jhg's DataGenerator.

using Newtonsoft.Json;

public struct DataCharacter : IBaseData
{
    [JsonProperty(PropertyName = "id")]
    private readonly int id;
    [JsonProperty(PropertyName = "PrefabName")]
    public readonly string PrefabName;
    [JsonProperty(PropertyName = "PrimaryWeaponAbility")]
    public readonly AbilityDefine PrimaryWeaponAbility;
    [JsonProperty(PropertyName = "ActiveSkill")]
    public readonly AbilityDefine ActiveSkill;
    [JsonProperty(PropertyName = "PassiveSkill")]
    public readonly AbilityDefine PassiveSkill;
    [JsonProperty(PropertyName = "CustomBossCharacterInfo")]
    public readonly string CustomBossCharacterInfo;
	
	public int Id => id;
    public bool IsNull => id == 0;
}
