#pragma warning disable 0649
//This script is generated by jhg's DataGenerator.

using Newtonsoft.Json;

public struct DataCharacterParts : IBaseData
{
    [JsonProperty(PropertyName = "id")]
    private readonly int id;
    [JsonProperty(PropertyName = "Category")]
    public readonly CharacterPartsCategory Category;
    [JsonProperty(PropertyName = "PartsType")]
    public readonly CharacterPartsType PartsType;
    [JsonProperty(PropertyName = "PartsName")]
    public readonly string PartsName;
    [JsonProperty(PropertyName = "ColorCode")]
    public readonly string ColorCode;
	
	public int Id => id;
    public bool IsNull => id == 0;
}
