#pragma warning disable 0649
//This script is generated by jhg's DataGenerator.

using Newtonsoft.Json;

public struct DataAbility : IBaseData
{
    [JsonProperty(PropertyName = "id")]
    private readonly int id;
    [JsonProperty(PropertyName = "SlotType")]
    public readonly AbilitySlotType SlotType;
    [JsonProperty(PropertyName = "CastingType")]
    public readonly CastingType CastingType;
    [JsonProperty(PropertyName = "BattleEvents")]
    public readonly BattleEventDefine[] BattleEvents;
    [JsonProperty(PropertyName = "TriggerType")]
    public readonly BattleEventTriggerType TriggerType;
    [JsonProperty(PropertyName = "TargetType")]
    public readonly BattleEventTargetType TargetType;
    [JsonProperty(PropertyName = "PrefabName")]
    public readonly string PrefabName;
    [JsonProperty(PropertyName = "HitEffectPrefabName")]
    public readonly string HitEffectPrefabName;
	
	public int Id => id;
    public bool IsNull => id == 0;
}
