#pragma warning disable 0649
//This script is generated by jhg's DataGenerator.

using Newtonsoft.Json;

public struct DataBalance : IBaseData
{
    [JsonProperty(PropertyName = "id")]
    private readonly int id;
    [JsonProperty(PropertyName = "nameId")]
    private readonly string nameId;
    [JsonProperty(PropertyName = "Values")]
    public readonly float[] Values;
    [JsonProperty(PropertyName = "ValueCount")]
    public readonly int ValueCount;
	
	public int Id => id;
    public string NameId => nameId;
    public bool IsNull => id == 0 || string.IsNullOrEmpty(nameId);
}
