#pragma warning disable 0649
//This script is generated by jhg's DataGenerator.

using Newtonsoft.Json;

public struct DataCharacter : IBaseData
{
    [JsonProperty(PropertyName = "id")]
    private readonly int id;
    [JsonProperty(PropertyName = "nameId")]
    private readonly string nameId;
    [JsonProperty(PropertyName = "PrefabName")]
    public readonly string PrefabName;
    [JsonProperty(PropertyName = "Default_Weapon")]
    public readonly AbilityDefine Default_Weapon;
    [JsonProperty(PropertyName = "ActiveSkill")]
    public readonly AbilityDefine ActiveSkill;
    [JsonProperty(PropertyName = "PassiveSkill")]
    public readonly AbilityDefine PassiveSkill;
	
	public int Id => id;
    public string NameId => nameId;
    public bool IsNull => id == 0 || string.IsNullOrEmpty(nameId);
}
