#pragma warning disable 0649
//This script is generated by jhg's DataGenerator.

using Newtonsoft.Json;

public struct DataAbility : IBaseData
{
    [JsonProperty(PropertyName = "id")]
    private readonly int id;
    [JsonProperty(PropertyName = "nameId")]
    private readonly string nameId;
    [JsonProperty(PropertyName = "Type")]
    public readonly AbilityType Type;
    [JsonProperty(PropertyName = "BattleEvent")]
    public readonly BattleEventDefine BattleEvent;
	
	public int Id => id;
    public string NameId => nameId;
    public bool IsNull => id == 0 || string.IsNullOrEmpty(nameId);
}
