#pragma warning disable 0649
//This script is generated by jhg's DataGenerator.

using Newtonsoft.Json;

public struct DataEnemyGroup : IBaseData
{
    [JsonProperty(PropertyName = "id")]
    private readonly int id;
    [JsonProperty(PropertyName = "Enemys")]
    public readonly CharacterDefine[] Enemys;
	
	public int Id => id;
    public bool IsNull => id == 0;
}
