#pragma warning disable 0649
//This script is generated by jhg's DataGenerator.

using Newtonsoft.Json;

public struct DataEnemyGroup : IBaseData
{
    [JsonProperty(PropertyName = "id")]
    private readonly int id;
    [JsonProperty(PropertyName = "MidBoss")]
    public readonly CharacterDefine MidBoss;
    [JsonProperty(PropertyName = "FinalBoss")]
    public readonly CharacterDefine FinalBoss;
    [JsonProperty(PropertyName = "Enemys")]
    private readonly CharacterDefine[][] enemys;

    public int EnemysCount => enemys?.Length ?? 0;

    public CharacterDefine[] GetEnemys(int index)
    {
        return (enemys != null && index >= 0 && index < enemys.Length)
               ? enemys[index] : null;
    }

	
	public int Id => id;
    public bool IsNull => id == 0;
}
