#pragma warning disable 0649
//This script is generated by jhg's DataGenerator.

using Newtonsoft.Json;

public struct DataBattleEvent : IBaseData
{
    [JsonProperty(PropertyName = "id")]
    private readonly int id;
    [JsonProperty(PropertyName = "nameId")]
    private readonly string nameId;
    [JsonProperty(PropertyName = "Type")]
    public readonly BattleEventType Type;
    [JsonProperty(PropertyName = "StatusEffect")]
    public readonly StatusEffectType StatusEffect;
    [JsonProperty(PropertyName = "AffectStat")]
    public readonly StatType AffectStat;
    [JsonProperty(PropertyName = "Value")]
    public readonly float[] Value;
    [JsonProperty(PropertyName = "Duration")]
    public readonly float[] Duration;
	
	public int Id => id;
    public string NameId => nameId;
    public bool IsNull => id == 0 || string.IsNullOrEmpty(nameId);
}
