#pragma warning disable 0649
//This script is generated by jhg's DataGenerator.

using Newtonsoft.Json;

public struct DataDungeon : IBaseData
{
    [JsonProperty(PropertyName = "id")]
    private readonly int id;
    [JsonProperty(PropertyName = "EnemyGroups")]
    public readonly EnemyGroupDefine[] EnemyGroups;
	
	public int Id => id;
    public bool IsNull => id == 0;
}
